version: '3'
services:

  proxy:
    image: traefik:v2.6
    container_name: proxy-traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure:5

networks:
  default:
    name: ${TRAEFIK_NETWORK:-proxy_network}
    external: true