services:
  plex:
    image: plexinc/pms-docker:${PLEX_TAG:-latest}
    container_name: plex
    environment:
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - TZ=${PLEX_TZ:-America/Toronto}
    ports:
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32400:32400/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - config:/config
      - content-anime:${PLEX_CONTENT_ANIME_INTERNAL:-/content/anime}:ro
      - content-anime-artwork:${PLEX_CONTENT_ANIME_ARTWORK_INTERNAL:-/content/anime-artwork}:ro
      - content-anime-movies:${PLEX_CONTENT_ANIME_MOVIES_INTERNAL:-/content/anime-movies}:ro
      - content-audio-books:${PLEX_CONTENT_AUDIO_BOOKS_INTERNAL:-/content/audio-books}:ro
      - content-concerts:${PLEX_CONTENT_CONCERTS_INTERNAL:-/content/concerts}:ro
      - content-movies:${PLEX_CONTENT_MOVIES_INTERNAL:-/content/movies}:ro
      - content-movies-4k:${PLEX_CONTENT_MOVIES_4K_INTERNAL:-/content/movies-4k}:ro
      - content-music:${PLEX_CONTENT_MUSIC_INTERNAL:-/content/music}:ro
      - content-photos:${PLEX_CONTENT_PHOTOS_INTERNAL:-/content/photos}:ro
      - content-tv:${PLEX_CONTENT_TV_INTERNAL:-/content/movies}:ro
      - content-tv-4k:${PLEX_CONTENT_TV_4K_INTERNAL:-/content/tv-4k}:ro
      - content-wallpapers:${PLEX_CONTENT_WALLPAPERS_INTERNAL:-/content/wallpapers}
      - transcoder:/transcode
    restart: on-failure:5

volumes:
  config:
    name: ${PLEX_CONFIG:-plex-config}
    external: true
  content-anime:
    name: ${PLEX_CONTENT_ANIME:-content-anime}
    external: true
  content-anime-artwork:
    name: ${PLEX_CONTENT_ANIME_ARTWORK:-content-anime-artwork}
    external: true
  content-anime-movies:
    name: ${PLEX_CONTENT_ANIME_MOVIES:-content-anime-movies}
    external: true
  content-audio-books:
    name: ${PLEX_CONTENT_AUDIO_BOOKS:-content-audio-books}
    external: true
  content-concerts:
    name: ${PLEX_CONTENT_CONCERTS:-content-concerts}
    external: true
  content-movies:
    name: ${PLEX_CONTENT_MOVIES:-content-movies}
    external: true
  content-movies-4k:
    name: ${PLEX_CONTENT_MOVIES_4K:-content-movies-4k}
    external: true
  content-music:
    name: ${PLEX_CONTENT_MUSIC:-content-music}
    external: true
  content-photos:
    name: ${PLEX_CONTENT_PHOTOS:-content-photos}
    external: true
  content-tv:
    name: ${PLEX_CONTENT_TV:-content-tv}
    external: true
  content-tv-4k:
    name: ${PLEX_CONTENT_TV_4K:-content-tv-4k}
    external: true
  content-wallpapers:
    name: ${PLEX_CONTENT_WALLPAPERS:-content-wallpapers}
    external: true
  transcoder:
    name: ${PLEX_TRANSCODER:-plex-transcoder}
    driver: local

networks:
  default:
    name: ${PLEX_NETWORK:-plex-network}
    external: true
