version: "3"
services:
  plex:
    image: plexinc/pms-docker:${PLEX_TAG:-latest}
    container_name: plex
    environment:
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - TZ=${PLEX_TZ:-America/Toronto}
    ports:
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32400:32400/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - config:/config
      - content:${PLEX_CONTENT_INTERNAL:-/content}
      - transcoder:/transcode
    restart: on-failure:5

volumes:
  config:
    name: ${PLEX_CONFIG:-plex_config}
    external: true
  content:
    name: ${PLEX_CONTENT:-content}
    external: true
  transcoder:
    name: plex_transcoder
    driver: local

networks:
  default:
    name: ${PLEX_NETWORK:-plex_network}
    external: true
