version: "3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=${TZ:-America/Toronto}
    ports:
      - "32400:32400"
    volumes:
      - config:/config
      - content:${PLEXSTACK_CONTENT_DIR:-/content}
      - transcoder:/transcode
    restart: on-failure:5

volumes:
  config:
    name: plexstack_config
    driver: local
  content:
    name: ${PLEXSTACK_CONTENT_VOLUME:-content}
    external: true
  transcoder:
    name: plexstack_transcoder
    driver: local
