version: "3"
services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    container_name: protonmail-bridge 
    ports: 
      - "1025:25"
      - "1143:143"
    volumes:
      - config:/root
    restart: on-failure:5
  
volumes:
  config:
    name: protonmail-bridge_config
    driver: local

