version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # https://github.com/pi-hole/docker-pi-hole/issues/1166
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "${PIHOLE_WEBPORT}:80/tcp"
    environment:
      - TZ=${PIHOLE_TZ:-America/Toronto}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD} # 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    # https://github.com/pi-hole/docker-pi-hole/issues/1166
    # dns:
      # - 127.0.0.1
      # - 1.1.1.1
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: on-failure:5

volumes:
  pihole-config:
  pihole-dnsmasq: