services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_HOST:-pgadmin.localhost}`)"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    restart: on-failure:5

volumes:
  pgadmin:
    name: pgadmin
    external: true

networks:
  default:
    name: ${PGADMIN_NETWORK:-proxy_network}
    external: true