services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${SWAG_TZ:-America/Toronto}
      - URL=${SWAG_DOMAIN:-example.com}
      - SUBDOMAINS=${SWAG_SUBDOMAINS:-www,}
      - ONLY_SUBDOMAINS=${SWAG_ONLY_SUBDOMAINS:-false}
      - VALIDATION=http
      - EMAIL= ${SWAG_EMAIL:-}
    volumes:
      - config:/config
    ports:
      - "443:443"
      - "80:80"
    restart: on-failure:5

volumes:
  config:
    name: ${SWAG_CONFIG:-swag_config}
    external: true

networks:
  default:
    name: ${SWAG_NETWORK:-proxy_network}
    external: true