version: "3.8"

networks:
  penpot:
    name: ${OUTLINE_NETWORK:-proxy_network}
    external: true

volumes:
  outline_data:
    name: outline_data
    external: true
  outline_postgres_v15:
    name: outline_postgres_v15
    external: true

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:${OUTLINE_VERSION:-0.74.0}
    container_name: outline
    restart: on-failure:5
    volumes:
      - outline_data:/var/lib/outline/data
    depends_on:
      - outline-postgres
      - outline-redis
    environment:
      - SECRET_KEY=${OUTLINE_SECRET}
      - UTILS_SECRET=${OUTLINE_UTILS_SECRET}
      - URL=${OUTLINE_URL}
      - PORT=${OUTLINE_PORT:-3000}
      - SMTP_HOST=${OUTLINE_SMTP_HOST}
      - SMTP_PORT=${OUTLINE_SMTP_PORT:-1025}
      - SMTP_USERNAME=${OUTLINE_SMTP_USERNAME}
      - SMTP_PASSWORD=${OUTLINE_SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${OUTLINE_SMTP_FROM_EMAIL}
      - SMTP_REPLY_EMAIL=${OUTLINE_SMTP_REPLY_EMAIL}
      - SMTP_SECURE=${OUTLINE_SMTP_SECURE:-false}
      - DATABASE_URL=postgres://user:pass@outline-postgres:5432/outline
      - PGSSLMODE=disable
      - FILE_STORAGE=local
      - FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
      - REDIS_URL=redis://outline-redis:6379

  outline-redis:
    image: redis:7-alpine
    container_name: outline-redis
    restart: on-failure:5

  outline-postgres:
    image: postgres:15-alpine
    container_name: outline-postgres
    volumes:
      - outline_postgres_v15:/var/lib/postgresql/data
    restart: on-failure:5
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
