version: "3.9"
services:
  valheim:
    image: emackie/steamcmd-valheim
    container_name: valheim
    environment:
      - VALHEIM_SERVER_PATH=/valheim
      - VALHEIM_SERVER_SAV_DIR=/valheim_worlds
      - VALHEIM_SERVER_NAME=${VALHEIM_SERVER_NAME:-My Server}
      - VALHEIM_SERVER_WORLD=${VALHEIM_SERVER_WORLD:-Dedicated}
      - VALHEIM_SERVER_PASS=${VALHEIM_SERVER_PASS:-secret}
      - VALHEIM_SERVER_PUBLIC=${VALHEIM_SERVER_PUBLIC:-1}
    volumes:
      - valheim_server:/valheim
      - valheim_worlds:/valheim_worlds
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    restart: on-failure:5

volumes:
  valheim_server:
    name: ${VALHEIM_SERVER_VOLUME:-valheim_server}
    external: true
  valheim_worlds:
    name: ${VALHEIM_WORLDS_VOLUME:-valheim_worlds}
    external: true

networks:
  default:
    name: ${VALHEIM_NETWORK:-valheim_network}
    external: true