services:

  telegraf:
    image: telegraf:1.31-alpine
    container_name: telegraf
    command: --config-directory=/etc/telegraf/telegraf.d
    user: telegraf:${DOCKER_DAEMON_GRP_ID:-1}
    volumes:
      - telegraf_conf:/etc/telegraf/telegraf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    environment: 
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_ORGANIZATION=${INFLUX_ORGANIZATION}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    restart: on-failure:5

volumes:
  telegraf_conf:
    name: telegraf_conf
    driver: local
