version: '3'
services:

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: mediabox-lidarr
    hostname: mediabox-lidarr
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - lidarr:/config
      - content:/content
      - downloads:/downloads
    restart: on-failure:5

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: mediabox-radarr
    hostname: mediabox-radarr
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - radarr:/config
      - content:/content
      - downloads:/downloads
    restart: on-failure:5

  radarr-4k:
    image: ghcr.io/linuxserver/radarr
    container_name: mediabox-radarr-4k
    hostname: mediabox-radarr-4k
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - radarr-4k:/config
      - content:/content
      - downloads:/downloads
    restart: on-failure:5

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: mediabox-sonarr
    hostname: mediabox-sonarr
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - sonarr:/config
      - content:/content
      - downloads:/downloads
    restart: on-failure:5

  sonarr-4k:
    image: ghcr.io/linuxserver/sonarr
    container_name: mediabox-sonarr-4k
    hostname: mediabox-sonarr-4k
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - sonarr-4k:/config
      - content:/content
      - downloads:/downloads
    restart: on-failure:5

volumes:
  content:
    name: ${MEDIABOX_CONTENT_VOLUME:-content}
    external: true
  downloads:
    name: ${MEDIABOX_DOWNLOADS_VOLUME:-content_downloads}
    external: true
  lidarr:
    name: mediabox_lidarr
  radarr:
    name: mediabox_radarr
  radarr-4k:
    name: mediabox_radarr_4k
  sonarr:
    name: mediabox_sonarr
  sonarr-4k:
    name: mediabox_sonarr_4k

networks:
  default:
    name: ${MEDIABOX_NETWORK:-proxy_network}
    external: true