services:

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: mediabox-lidarr
    hostname: mediabox-lidarr
    environment:
      - TZ=${MEDIABOX_TZ:-America/Toronto}
    volumes:
      - lidarr:/config
      - music:${MEDIABOX_MUSIC_INTERNAL:-/content/music}
      - downloads:/downloads:ro
    restart: on-failure:5

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: mediabox-radarr
    hostname: mediabox-radarr
    environment:
      - TZ=${MEDIABOX_TZ:-America/Toronto}
    volumes:
      - radarr:/config
      - anime-movies:${MEDIABOX_ANIME_MOVIES_INTERNAL:-/content/anime-movies}
      - concerts:${MEDIABOX_CONCERTS_INTERNAL:-/content/concerts}
      - movies:${MEDIABOX_MOVIES_INTERNAL:-/content/movies}
      - downloads:/downloads:ro
    restart: on-failure:5

  radarr-4k:
    image: lscr.io/linuxserver/radarr
    container_name: mediabox-radarr-4k
    hostname: mediabox-radarr-4k
    environment:
      - TZ=${MEDIABOX_TZ:-America/Toronto}
    volumes:
      - radarr-4k:/config
      - movies-4k:${MEDIABOX_MOVIES_4K_INTERNAL:-/content/movies-4k}
      - downloads:/downloads
    restart: on-failure:5

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: mediabox-sonarr
    hostname: mediabox-sonarr
    environment:
      - TZ=${MEDIABOX_TZ:-America/Toronto}
    volumes:
      - sonarr:/config
      - anime:${MEDIABOX_ANIME_INTERNAL:-/content/anime}
      - tv:${MEDIABOX_TV_INTERNAL:-/content/tv}
      - downloads:/downloads:ro
    restart: on-failure:5

  sonarr-4k:
    image: lscr.io/linuxserver/sonarr
    container_name: mediabox-sonarr-4k
    hostname: mediabox-sonarr-4k
    environment:
      - TZ=${MEDIABOX_TZ:-America/Toronto}
    volumes:
      - sonarr-4k:/config
      - tv-4k:${MEDIABOX_TV_4K_INTERNAL:-/content/tv-4k}
      - downloads:/downloads:ro
    restart: on-failure:5

volumes:
  anime:
    name: ${MEDIABOX_ANIME_VOLUME:-anime}
    external: true
  anime-movies:
    name: ${MEDIABOX_ANIME_MOVIES_VOLUME:-anime-movies}
    external: true
  concerts:
    name: ${MEDIABOX_CONCERTS_VOLUME:-concerts}
    external: true
  downloads:
    name: ${MEDIABOX_DOWNLOADS_VOLUME:-downloads}
    external: true
  movies:
    name: ${MEDIABOX_MOVIES_VOLUME:-movies}
    external: true
  movies-4k:
    name: ${MEDIABOX_MOVIES_4K_VOLUME:-movies-4k}
    external: true
  music:
    name: ${MEDIABOX_MUSIC_VOLUME:-music}
    external: true
  lidarr:
    name: mediabox_lidarr
    external: true
  radarr:
    name: mediabox_radarr
    external: true
  radarr-4k:
    name: mediabox_radarr_4k
    external: true
  sonarr:
    name: mediabox_sonarr
    external: true
  sonarr-4k:
    name: mediabox_sonarr_4k
    external: true
  tv:
    name: ${MEDIABOX_TV_VOLUME:-tv}
    external: true
  tv-4k:
    name: ${MEDIABOX_TV_4K_VOLUME:-tv-4k}
    external: true

networks:
  default:
    name: ${MEDIABOX_NETWORK:-proxy-network}
    external: true